[settings]
posthooks = [ 
    "chmod +x ~/.local/bin/gendl",
    "chmod +x ~/.local/bin/switch-input",
]

[settings.dots]
gendl = { source = "bin/gendl.sh", target = ".local/bin/gendl" }
switch-input = { source = "bin/switch-input.sh", target = ".local/bin/switch-input" }