dotfiles_dir = "dotfiles"

import = [
    { path = "code/code.toml" },
    { path = "easyeffects/easyeffects.toml" },
    { path = "bin/bin.toml" },
    { path = "backup/backup.toml" },
    { path = "katarl/katarl.toml" },
    { path = "podman/podman.toml" },
    { path = "opencode/opencode.toml" },
]

[settings.dots]
atuin = { source = "atuin/config.toml", target = ".config/atuin/config.toml" }
bash = { source = "bash/bashrc", target = ".bashrc" }
blesh = { source = "blesh/blerc", target = ".blerc" }
git = { source = "git/gitconfig", target = ".gitconfig" }
electron = { source = "electron/electron-flags.conf", target = ".config/electron-flags.conf" }
chromium = { source = "chromium/chromium-flags.conf", target = ".config/chromium-flags.conf" }
htop = { source = "htop/htoprc", target = ".config/htop/htoprc" }
s3fs = { source = "s3fs/backblaze.service", target = ".config/systemd/user/backblaze.service" }
