[settings.dots]
code_user_settings = { source = "code/settings.json", target = ".config/Code - OSS/User/settings.json" }
code_flags = { source = "code/code-flags.conf", target = ".config/code-flags.conf" }