[settings]
posthooks = [
    "systemctl --user daemon-reload",
    "systemctl --user enable --now offsite.timer",
]

[settings.dots]
backup_offsite_script = { source = "backup/offsite.sh", target = ".local/bin/offsite" }
backup_service = { source = "backup/offsite.service", target = ".config/systemd/user/offsite.service" }
backup_timer = { source = "backup/offsite.timer", target = ".config/systemd/user/offsite.timer" }