[settings]
posthooks = [
    "systemctl --user daemon-reload",
    "systemctl --user enable --now offsite.timer",
]

[settings.dots]
offsite = { source = "backup/offsite.sh", target = ".local/bin/offsite" }
service = { source = "backup/offsite.service", target = ".config/systemd/user/offsite.service" }
timer = { source = "backup/offsite.timer", target = ".config/systemd/user/offsite.timer" }