#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ll='ls -alh'
alias uctl='systemctl --user'
pwgen() { /usr/bin/env pwgen -c -y -1 ${1:-24} ${2:-1}; }
PS1='[\u@\h \W]\$ '

export EDITOR=vim

[[ -f /usr/share/bash-preexec/bash-preexec.sh ]] && source /usr/share/bash-preexec/bash-preexec.sh
eval "$(atuin init bash --disable-up-arrow)"

export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"

export HASS_SERVER=https://home.brodersen.family
export HASS_TOKEN=$(secret-tool lookup url 'https://home.brodersen.family')
export OPENROUTER_API_KEY=$(secret-tool lookup service openrouter)
export PATH="${HOME}/.local/bin:$PATH"
source <(_HASS_CLI_COMPLETE=bash_source hass-cli)

export CYBERDROP_DIR=${HOME}/cyberdrop
export CYBERDROP_DL_DIR=${HOME}/bb/pr0zn/cyberdrop

alias cbdl='cyberdrop-dl --appdata-folder ${CYBERDROP_DIR}/appdata'
alias cbdlnow='cyberdrop-dl --appdata-folder ${CYBERDROP_DIR}/appdata --config-file ./config.yaml'

export PATH="$PATH:/opt/rocm/bin"

export PATH="${HOME}/.cargo/bin:$PATH"

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

alias bb=b2
alias k='kubectl'
alias watch='watch '

[[ ! ${BLE_VERSION-} ]] || ble-attach
